/**************************THIS FILE WAS AUTOGENERATED**************************/
#include <stddef.h>
static char const *user_argv[] = {"642_TAs_are_great", "0", NULL};
static const int user_argc = 2;
/*******************************************************************************/